module.exports = {
    all: {
        list_camp: 'Список лагерей',
        add_camp: 'Добавить лагерь',
        add_camp_confirm: 'Вы хотите добавить новый лагерь?',
        add_tariff_confirm: 'Вы хотите добавить новую смену?',
        delete_image_confirm: 'Вы хотите удалить это изображение?',
        delete_tariff_confirm: 'Вы хотите удалить эту смену?',
        list_program: 'Список программ',
        add_program: 'Создать программу',
        active_programs: 'Действующие программы',
        delete: 'Удалить',
        edit: 'Редактировать',
        apply: 'Применить',
        cancel: 'Отмена',
        close: 'Закрыть',
        days: ['день', 'дня', 'дней'],
        rub_small: 'р.',
        add_photo: 'Добавить фото',
        delete_photo: 'Удалить фото',
        tariff: 'Смена',
        camp_theme: 'Тематика лагеря',
        sertificate_reestr_register: 'Свидетельство о внесении сведений о туроператоре в единый федеральный реестр',
        add_sertificate: 'Добавить свидетельство',
        input_address_hint: "После введения адреса\r\n система автоматически\r\n сформирует карту",
    },
    camp: {
        id_ucase: 'ID',
        inn: 'ИНН',
        video_of_camp: 'Видеообращение лагеря или видео о лагере',
        short_name: 'Краткое название',
        legal_name: 'Юридическое название',
        foundation_date: 'Основан',
        place_address: 'Адрес местонахождения',
        office_description: 'Как проехать до офиса и время работы',
        office_description_sample: 'Например: Выйти из метро и пойти под аркой. Офис работает в будние дни с 10 до 18. Выходной воскресенье.',
        param_type_1: 'Размещение',
        param_type_2: 'Питание',
        param_type_3: 'Инфраструктура',
        param_type_4: 'Охрана',
        param_type_5: 'Мед.обслуживание',
    }
}